[package]
name = "medweb3"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.17.0" # Latest compatible Solana program crate
borsh = "0.10.3"         # Borsh for serialization/deserialization
borsh-derive = "0.10.3"  # Derive macros for Borsh
